Add missing include for size_t
Fixes compile error:
[...]
g++ -c  -g TokenArray.cpp
In file included from TokenArray.cpp:1:0:
TokenArray.h:20:4: error: ‘size_t’ does not name a type
    size_t size() {return m_tokens.size();}
    ^
TokenArray.h:41:4: error: ‘size_t’ does not name a type
    size_t m_index;
    ^